c_compiler: vs2017
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: vs2017
fortran_compiler: flang
ignore_build_only_deps: numpy
lua: '5'
metis: '5.1'
numpy: '1.11'
openblas: 0.3.5
perl: 5.26.0
pin_run_as_build:
  python: {min_pin: x.x, max_pin: x.x}
  r-base: {min_pin: x.x.x, max_pin: x.x.x}
  metis: {max_pin: x.x}
  openblas: {max_pin: x.x.x}
  vc: {max_pin: x}
python: '3.6'
r_base: '3.4'
target_platform: win-64
vc: '14'
zip_keys:
- [vc, c_compiler, cxx_compiler]
